/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d1",
        "primary": "#001e40",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "surface-tint": "#3a5f94",
        "on-surface-variant": "#43474f",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed": "#261900",
        "tertiary": "#141f30",
        "secondary-fixed": "#ffdea5",
        "on-primary-container": "#799dd6",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#001b3c",
        "surface-dim": "#d8dadc",
        "secondary": "#775a19",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#785a1a",
        "secondary-fixed-dim": "#e9c176",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#1f477b",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#111c2d",
        "primary-container": "#003366",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#a7c8ff",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#293446",
        "tertiary-fixed-dim": "#bcc7de",
        "surface-bright": "#f7f9fb",
        "on-tertiary-container": "#919cb3",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary": "#ffffff",
        "outline": "#737780",
        "surface-container-low": "#f2f4f6",
        "secondary-container": "#fed488",
        "primary-fixed": "#d5e3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Tajawal", "Manrope", "sans-serif"],
        body: ["IBM Plex Sans Arabic", "Work Sans", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
